import React from "react";

const sizeClasses = {
  txtInterRegular20: "font-inter font-normal",
  txtInterSemiBold26: "font-inter font-semibold",
  txtPoppinsRegular28: "font-normal font-poppins",
  txtPoppinsRegular32: "font-normal font-poppins",
  txtInterMedium28Gray70001: "font-inter font-medium",
  txtInterMedium12Gray70001: "font-inter font-medium",
  txtInterBold64: "font-bold font-inter",
  txtInterMedium12Gray70003: "font-inter font-medium",
  txtInterMedium12Gray70002: "font-inter font-medium",
  txtPoppinsRegular32WhiteA700: "font-normal font-poppins",
  txtPoppinsRegular30: "font-normal font-poppins",
  txtInterBold20Purple50001: "font-bold font-inter",
  txtInterExtraBold52: "font-extrabold font-inter",
  txtInterRegular8: "font-inter font-normal",
  txtInterExtraBold50: "font-extrabold font-inter",
  txtInterSemiBold20Black900: "font-inter font-semibold",
  txtInterRegular26: "font-inter font-normal",
  txtPoppinsRegular14WhiteA700: "font-normal font-poppins",
  txtPoppinsRegular14Black900: "font-normal font-poppins",
  txtInterRegular8Gray70001: "font-inter font-normal",
  txtInterSemiBold35: "font-inter font-semibold",
  txtPoppinsRegular14: "font-normal font-poppins",
  txtPoppinsRegular15: "font-normal font-poppins",
  txtPoppinsRegular16: "font-normal font-poppins",
  txtInterBold50: "font-bold font-inter",
  txtInterSemiBold40: "font-inter font-semibold",
  txtInterSemiBold42: "font-inter font-semibold",
  txtInterBold45Black900: "font-bold font-inter",
  txtInterRegular12: "font-inter font-normal",
  txtInterRegular14: "font-inter font-normal",
  txtPoppinsRegular10Black900: "font-normal font-poppins",
  txtInterRegular16: "font-inter font-normal",
  txtPoppinsLight14: "font-light font-poppins",
  txtPoppinsLight12: "font-light font-poppins",
  txtPoppinsLight17: "font-light font-poppins",
  txtIstokWebBold12: "font-bold font-istokweb",
  txtInterMedium45: "font-inter font-medium",
  txtInterBold48: "font-bold font-inter",
  txtInterSemiBold45: "font-inter font-semibold",
  txtPoppinsLight10: "font-light font-poppins",
  txtInterBold45: "font-bold font-inter",
  txtInterSemiBold50: "font-inter font-semibold",
  txtPoppinsRegular10: "font-normal font-poppins",
  txtInterBold40: "font-bold font-inter",
  txtInterLight16: "font-inter font-light",
  txtPoppinsRegular11: "font-normal font-poppins",
  txtPoppinsRegular12: "font-normal font-poppins",
  txtInterLight12: "font-inter font-light",
  txtPoppinsRegular96: "font-normal font-poppins",
  txtInterExtraBold28WhiteA700: "font-extrabold font-inter",
  txtInterRegular30Gray700b2: "font-inter font-normal",
  txtInterMedium12Gray60002: "font-inter font-medium",
  txtDigitalNumbersRegular96: "font-digitalnumbers font-normal",
  txtInterBold36: "font-bold font-inter",
  txtInterBold32: "font-bold font-inter",
  txtInterRegular26Bluegray800: "font-inter font-normal",
  txtInterBold35: "font-bold font-inter",
  txtDMSansMedium16: "font-dmsans font-medium",
  txtInterLight24: "font-inter font-light",
  txtInterLight25: "font-inter font-light",
  txtInterLight22: "font-inter font-light",
  txtPoppinsMedium40: "font-medium font-poppins",
  txtInterMedium40: "font-inter font-medium",
  txtInterMedium24: "font-inter font-medium",
  txtInterBold28: "font-bold font-inter",
  txtInterMedium22: "font-inter font-medium",
  txtInterMedium28: "font-inter font-medium",
  txtInterMedium25: "font-inter font-medium",
  txtPoppinsRegular16Bluegray90001: "font-normal font-poppins",
  txtInterBold20: "font-bold font-inter",
  txtPoppinsMedium32: "font-medium font-poppins",
  txtInterLight30: "font-inter font-light",
  txtInterMedium25Gray700: "font-inter font-medium",
  txtInterMedium20Black900: "font-inter font-medium",
  txtInterMedium19: "font-inter font-medium",
  txtInterMedium20Gray700cc: "font-inter font-medium",
  txtInterMedium12: "font-inter font-medium",
  txtInterMedium10: "font-inter font-medium",
  txtInterMedium16: "font-inter font-medium",
  txtInterMedium17: "font-inter font-medium",
  txtInterMedium14: "font-inter font-medium",
  txtInterRegular20Black900: "font-inter font-normal",
  txtInterMedium20: "font-inter font-medium",
  txtIstokWebRegular12: "font-istokweb font-normal",
  txtInterBold40WhiteA700: "font-bold font-inter",
  txtIstokWebRegular14: "font-istokweb font-normal",
  txtPoppinsLight14WhiteA700: "font-light font-poppins",
  txtInterBold40Bluegray900: "font-bold font-inter",
  txtInterSemiBold40Black900: "font-inter font-semibold",
  txtInterSemiBold20Amber500: "font-inter font-semibold",
  txtPoppinsRegular48: "font-normal font-poppins",
  txtInterBold50Black900: "font-bold font-inter",
  txtInterBold48Red50: "font-bold font-inter",
  txtInterBold80: "font-bold font-inter",
  txtInterExtraBold30: "font-extrabold font-inter",
  txtInterRegular26WhiteA700: "font-inter font-normal",
  txtPoppinsMedium18: "font-medium font-poppins",
  txtInterBold28WhiteA700: "font-bold font-inter",
  txtInterRegular30: "font-inter font-normal",
  txtInterSemiBold12: "font-inter font-semibold",
  txtInterSemiBold16: "font-inter font-semibold",
  txtInterSemiBold17: "font-inter font-semibold",
  txtInterExtraBold28: "font-extrabold font-inter",
  txtInterExtraBold26: "font-extrabold font-inter",
  txtInterBold75: "font-bold font-inter",
  txtInterSemiBold22: "font-inter font-semibold",
  txtInterSemiBold20: "font-inter font-semibold",
  txtPoppinsRegular14Gray50005: "font-normal font-poppins",
};

const Text = ({ children, className = "", size, as, ...restProps }) => {
  const Component = as || "p";

  return (
    <Component
      className={`text-left ${className} ${size && sizeClasses[size]}`}
      {...restProps}
    >
      {children}
    </Component>
  );
};

export { Text };
